# Server Configuration
server.port=8097
server.servlet.context-path=/api

# Spring Configuration
spring.application.name=springboot-jenkins-docker-demo
spring.profiles.active=dev

# Knife4j Configuration
knife4j.enable=true
knife4j.setting.language=zh_cn

